### ISSUE TITLE
usage/

### ISSUE THREAD

**Issue by darknodi** [d4rkerNight/TakeDown#1]

**Comment by d4rkerNight** [comment]
Is this not enough?
I will update the description if that is what you meant.

From the code:
fprintf(stderr, W "\nUsage: takedown requests targets_file victim\n" N);
fprintf(stderr, "\nEx: takedown 10000 wp_pingback www.victim.com\n\n");

**Comment by darknodi** [comment]
@d4rkerNight the usage from this script file, before terminal linux. 

this script file, can takedown the website that contains, php.

**Comment by d4rkerNight** [comment]
"website that contains, php" What? Did you understand the code?
Anyway, thank you for bringing this issue to my attention, I guess not many people can read simple C code. When I have time I will update the README.md.

**Comment by darknodi** [comment]
you can make the start menu with bash.sh script .

like . 

takeout.sh domain.com
loading.php 
sending nodes.....
domain.com down..........

i will keep this silently.

god keeps you one day from one princess, :) 

bash script menu. number one.

chmod a+x * 

bash takeout.sh

domain: domain.com
etc.etc

domain.com is down. 

i will keep this silently. from eyes from the others. @d4rkerNight

**Comment by darknodi** [comment]
apt install make, cmake, clang, gcc, g++

gcc * 
g++ *
make 
make all 

in the bash script 
chmod a+x file.php

**Comment by d4rkerNight** [comment]
"you can make the start menu with bash.sh script" lol, why should I use bash when this is C language?!? Please stop!! I can stand anymore to noobs!!
